# fly.toml para microservicio Gestión (TCP)
app = "gestion-ms"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  NODE_ENV = "production"

[[services]]
  protocol = "tcp"
  internal_port = 4010
  processes = ["app"]

  [[services.ports]]
    port = 4010

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
